const MODEL="gpt-image-2";
const HTML=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>شعوري.. لوحة</title><style>
body{margin:0;background:linear-gradient(135deg,#03251a,#08734b);color:#fff;font-family:Tahoma,Arial,sans-serif}main{max-width:850px;margin:auto;padding:24px}.box{background:#ffffff12;border:1px solid #ffffff22;border-radius:24px;padding:22px;margin:16px 0}h1{text-align:center;font-size:42px}.tag{text-align:center;font-weight:800;color:#e4c66b;font-size:20px}label{display:block;font-weight:bold;margin:12px 0 6px}input,textarea{width:100%;box-sizing:border-box;padding:13px;border-radius:14px;border:1px solid #ffffff33;background:#001c12;color:white;font:inherit}textarea{min-height:130px}.chips{display:flex;gap:8px;flex-wrap:wrap}.chip{padding:9px 13px;border-radius:20px;border:1px solid #ffffff33;background:#ffffff12;color:#fff;cursor:pointer}.active{background:#e4c66b;color:#052116}button.main{width:100%;padding:15px;margin-top:16px;border:0;border-radius:15px;background:#e4c66b;color:#062117;font-weight:900;font-size:18px}#status{text-align:center;min-height:28px;margin:12px}.result img{width:100%;border-radius:20px}footer{text-align:center;opacity:.8;padding:20px}</style></head><body><main>
<div class="box"><div class="tag">🇸🇦 اليوم الوطني السعودي 96 · 2026</div><h1>شعوري.. لوحة 🎨</h1><div class="tag">وطن بعيون الذكاء الاصطناعي</div><p style="text-align:center">عزّنا بطبعنا</p></div>
<div class="box"><label>اسم المشاركة</label><input id="name" placeholder="اكتبي الاسم"><label>الشعور</label><div class="chips"><button class="chip">فخر</button><button class="chip">انتماء</button><button class="chip">أمل</button><button class="chip">طموح</button><button class="chip">امتنان</button><button class="chip">مستقبل</button><button class="chip">اعتزاز</button><button class="chip">فرح</button></div><label>صفي شعورك تجاه الوطن</label><textarea id="feel" placeholder="اكتبي شعورك بكلماتك..."></textarea><button class="main" id="go">🎨 ارسم شعوري</button><div id="status"></div><div class="result" id="result" hidden><img id="img"><button id="save" style="margin-top:10px;padding:12px">⬇️ حفظ الصورة</button></div></div>
<footer>المدرسة المتوسطة السابعة والأربعون · إدارة تعليم المدينة المنورة<br>إعداد وتنفيذ: جوهره الجابري</footer></main>
<script>let emotion="";document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");emotion=b.textContent});go.onclick=async()=>{let feelings=feel.value.trim();if(!feelings&&!emotion){status.textContent="اكتبي شعورك أو اختاري شعورًا أولًا.";return}go.disabled=true;status.textContent="جاري إنشاء لوحة واقعية بالذكاء الاصطناعي...";try{let r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({feelings,emotion})}),d=await r.json();if(!r.ok)throw Error(d.error||"تعذر إنشاء الصورة");img.src="data:image/png;base64,"+d.image;result.hidden=false;status.textContent="تم إنشاء اللوحة."}catch(e){status.textContent="⚠️ "+e.message}finally{go.disabled=false}};save.onclick=()=>{let a=document.createElement("a");a.href=img.src;a.download="شعوري-لوحة-اليوم-الوطني-96.png";a.click()};</script></body></html>`;

function makePrompt(b){return `Create ONE original photorealistic editorial photograph inspired by Saudi National Day 96 (2026), official theme "عزّنا بطبعنا". Make it clearly Saudi and clearly suitable for a National Day 96 school exhibition. Selected emotion: ${b.emotion||"فخر"}. Participant feeling: ${String(b.feelings||"").slice(0,1200)}. Use authentic contemporary Saudi people, places and atmosphere, natural realistic lighting and skin, cinematic but believable photography, subtle Saudi green and white cues. Express the specific feeling rather than making a generic tourism image. Do NOT put any words, letters, numbers, logos, captions or watermarks in the image. NEGATIVE: cartoon, anime, illustration, vector, clipart, generic stock photo, fantasy, distorted people, deformed hands, incorrect Saudi flag, Founding Day brown identity, National Day 95, old campaign identity, text, Arabic letters, English letters, numbers, logo, watermark, captions, signs, gibberish.`}
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=utf-8"}});
export default{async fetch(req,env){let u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/")return new Response(HTML,{headers:{"content-type":"text/html;charset=utf-8"}});if(req.method==="POST"&&u.pathname==="/api/generate"){try{if(!env.OPENAI_API_KEY)return J({error:"لم يتم إعداد OPENAI_API_KEY في السيرفر."},500);let b=await req.json();let r=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{"Authorization":"Bearer "+env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,prompt:makePrompt(b),size:"1024x1024",quality:"high",output_format:"png"})});let d=await r.json();if(!r.ok)return J({error:d?.error?.message||"تعذر توليد الصورة من OpenAI."},r.status);let im=d?.data?.[0]?.b64_json;if(!im)return J({error:"لم تُرجع خدمة الصور الصورة."},502);return J({image:im})}catch(e){return J({error:String(e.message||e)},500)}}return new Response("Not found",{status:404})}};